import type { AuthorityRun } from '../../types/authority';

export function exportRunToMarkdown(run: AuthorityRun): string {
  const { source, positioning, analysis, assets, qualityGate, calendar } = run;
  const lines: string[] = [];

  lines.push(`# ${source.title}`);
  lines.push('');
  lines.push(`*Generated by CreatorOS — Authority Engine · ${new Date(run.createdAt).toLocaleString()}*`);
  if (source.url) lines.push(`*Source: ${source.url}*`);
  lines.push('');

  lines.push('## Positioning');
  lines.push(`- **Audience:** ${positioning.audience}`);
  lines.push(`- **Positioning:** ${positioning.positioning}`);
  lines.push(`- **Series:** ${positioning.seriesName}`);
  lines.push(`- **Calendar week:** ${positioning.calendarWeek}`);
  lines.push(`- **Offer:** ${positioning.offer}`);
  lines.push(`- **CTA goal:** ${positioning.ctaGoal}`);
  lines.push(`- **Platforms:** ${positioning.platforms.join(', ')}`);
  lines.push(`- **Content goals:** ${positioning.contentGoals.join(', ')}`);
  lines.push('');

  if (analysis) {
    lines.push('## Key Points');
    analysis.keyPoints.forEach((p) => lines.push(`- ${p}`));
    lines.push('');

    lines.push('## Excluded Noise');
    analysis.excludedNoise.forEach((p) => lines.push(`- ${p}`));
    lines.push('');

    lines.push('## System Insight');
    lines.push(`> ${analysis.systemInsight}`);
    lines.push('');

    lines.push('## Detected Friction');
    analysis.detectedFriction.forEach((p) => lines.push(`- ${p}`));
    lines.push('');

    lines.push('## Anti-Pattern');
    lines.push(`**${analysis.antiPattern}**`);
    lines.push('');

    lines.push('## Metric Lens');
    analysis.metricLens.forEach((p) => lines.push(`- ${p}`));
    lines.push('');

    lines.push('## Content Angles');
    analysis.contentAngles.forEach((p) => lines.push(`- ${p}`));
    lines.push('');

    lines.push('## Affected Engineering Zones');
    lines.push(analysis.affectedZones.map((z) => `\`${z}\``).join(', '));
    lines.push('');
  }

  if (assets.length > 0) {
    lines.push('## Content Assets');
    assets.forEach((asset) => {
      lines.push('');
      lines.push(`### ${asset.title}`);
      lines.push(`*${asset.goal} · ${asset.platform} · ${asset.wordCount} words*`);
      lines.push('');
      lines.push(asset.body);
      lines.push('');
      if (asset.cta) lines.push(`**CTA:** ${asset.cta}`);
    });
    lines.push('');
  }

  if (qualityGate) {
    lines.push('## Quality Gate');
    const rows: Array<[string, boolean]> = [
      ['Hook in first sentence', qualityGate.hookInFirstSentence],
      ['No hype', qualityGate.noHype],
      ['Clear audience', qualityGate.clearAudience],
      ['System insight present', qualityGate.systemInsightPresent],
      ['CTA present', qualityGate.ctaPresent],
      ['Positioning visible', qualityGate.positioningVisible],
      ['Platform format valid', qualityGate.platformFormatValid],
      ['Technical claims safe', qualityGate.technicalClaimsSafe],
    ];
    rows.forEach(([label, ok]) => lines.push(`- ${ok ? '✅' : '❌'} ${label}`));
    if (qualityGate.notes.length > 0) {
      lines.push('');
      lines.push('**Notes:**');
      qualityGate.notes.forEach((n) => lines.push(`- ${n}`));
    }
    lines.push('');
  }

  if (calendar.length > 0) {
    lines.push('## Calendar Entries');
    lines.push('| Week | Day | Platform | Goal | Title |');
    lines.push('|---|---|---|---|---|');
    calendar.forEach((e) => {
      lines.push(`| ${e.week} | ${e.day} | ${e.platform} | ${e.goal} | ${e.title} |`);
    });
    lines.push('');
  }

  return lines.join('\n');
}
