/**
 * CreatorOS Asset Identity Model
 *
 * Four distinct identity concepts — never conflate them:
 *
 * blueprint_hash   Fingerprint of the full blueprint spec (fields, states, fixtures).
 *                  Changes whenever the blueprint structure or content changes.
 *                  Computed by hashBlueprint(). Tracks WHICH blueprint version produced
 *                  an asset, but must NOT be used as the asset's own identity.
 *
 * asset_id         Semantic identity of the asset. Stable across blueprint refinements
 *                  as long as slug, state, and version have not changed. A fixture text
 *                  correction must NOT produce a new asset_id — otherwise analytics,
 *                  caching, and deduplication break silently.
 *                  Formula: asset_{slug}_{state}_v{version}
 *
 * artifact_hash    Fingerprint of the generated artifact content (hook, body, CTA, etc.).
 *                  Reserved for InstagramAssetV1 / Sprint 5B. Undefined until content
 *                  is actually generated by the compiler.
 *
 * run_id           Unique identifier per pipeline execution. Changes on every run.
 *                  Used for audit trails, debug sessions, and distinguishing re-runs
 *                  of the same semantic asset.
 *                  Formula: run_{unix_ms}
 */

export type AssetId = string;
export type RunId = string;
export type ArtifactHash = string;

export function generateAssetId(
  slug: string,
  state: string,
  version: number,
): AssetId {
  return `asset_${slug}_${state}_v${version}`;
}

export function generateRunId(): RunId {
  return `run_${Date.now()}`;
}
